### ISSUE TITLE
Quorvo iOS compatibility 

### ISSUE THREAD

**Issue by gilbertgit** [br101/libdeca#2]
I was wondering if the lib had compatibility with the Quorvo NI app.
I'm using an ESP32C6 and I'm able to get ble connection and communication with the Quorvo app. Looks like my next set would be to provide the app with some config data: `NINearbyAccessoryConfiguration`. I can't seem to find anywhere what this would look like exactly. The iOS docs give me a Message Format but the last section is `UWBConfigData` but does not define what that is... From what I can find in the Quorvo source, `niq_populate_accessory_uwb_config_data` is what I would need to call to get that data. Is this implemented in your lib?

**Comment by br101** [comment]
Hi! Yes I have implemented this, but not published, send me an email.

**Comment by br101** [comment]
did you receive my email?

**Comment by Sasha567898** [comment]
Hi! I'm currently working with the ESP32-DW3000 module from Makerfabs and am also exploring compatibility with the Qorvo NI App. I'm very interested in understanding how your implementation works. Would it be possible for you to share more details or point me in the direction of your implementation?

**Comment by br101** [comment]
You can check this thread here: https://forum.qorvo.com/t/apple-ni-configuration-data-frame/10796/44
Basically the NI handshake is only the beginning. Then you need to implement the FIRA standard. I'm pretty sure the only way to do that is to buy access to the standard from the FIRA consortium.
